//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.16 at 11:51:40 AM CET 
//


package nl.naturalis.oaipmh.api.jaxb.abcd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Elements only used for units in culture collections
 * 			
 * 
 * <p>Java class for CultureCollectionUnit complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CultureCollectionUnit">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OrganismType" type="{http://www.tdwg.org/schemas/abcd/2.06}String" minOccurs="0"/>
 *         &lt;element name="InfrasubspecificName" type="{http://www.tdwg.org/schemas/abcd/2.06}String" minOccurs="0"/>
 *         &lt;element name="CultureNames" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CultureName" type="{http://www.tdwg.org/schemas/abcd/2.06}StringL" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Strain" type="{http://www.tdwg.org/schemas/abcd/2.06}String" minOccurs="0"/>
 *         &lt;element name="SerovarOrSerotype" type="{http://www.tdwg.org/schemas/abcd/2.06}String" minOccurs="0"/>
 *         &lt;element name="Pathovar" type="{http://www.tdwg.org/schemas/abcd/2.06}String" minOccurs="0"/>
 *         &lt;element name="Mutant" type="{http://www.tdwg.org/schemas/abcd/2.06}String" minOccurs="0"/>
 *         &lt;element name="Genotype" type="{http://www.tdwg.org/schemas/abcd/2.06}String" minOccurs="0"/>
 *         &lt;element name="GrowthConditions" type="{http://www.tdwg.org/schemas/abcd/2.06}StringL" minOccurs="0"/>
 *         &lt;element name="GrowthConditionAtomised" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CultureMedium" type="{http://www.tdwg.org/schemas/abcd/2.06}StringL" minOccurs="0"/>
 *                   &lt;element name="Aerobicity" type="{http://www.tdwg.org/schemas/abcd/2.06}StringL" minOccurs="0"/>
 *                   &lt;element name="Temperature" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="TemperatureType">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *                                 &lt;enumeration value="Celsius"/>
 *                                 &lt;enumeration value="Fahrenheit"/>
 *                                 &lt;enumeration value="Absolute"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                           &lt;attribute name="scale" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="References" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Reference" type="{http://www.tdwg.org/schemas/abcd/2.06}Reference" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="FormOfSupply" type="{http://www.tdwg.org/schemas/abcd/2.06}StringL" minOccurs="0"/>
 *         &lt;element name="Applications" type="{http://www.tdwg.org/schemas/abcd/2.06}StringL" minOccurs="0"/>
 *         &lt;element name="Hazard" type="{http://www.tdwg.org/schemas/abcd/2.06}StringL" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CultureCollectionUnit", propOrder = {
    "organismType",
    "infrasubspecificName",
    "cultureNames",
    "strain",
    "serovarOrSerotype",
    "pathovar",
    "mutant",
    "genotype",
    "growthConditions",
    "growthConditionAtomised",
    "references",
    "formOfSupply",
    "applications",
    "hazard"
})
public class CultureCollectionUnit {

    @XmlElement(name = "OrganismType")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String organismType;
    @XmlElement(name = "InfrasubspecificName")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String infrasubspecificName;
    @XmlElement(name = "CultureNames")
    protected CultureCollectionUnit.CultureNames cultureNames;
    @XmlElement(name = "Strain")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String strain;
    @XmlElement(name = "SerovarOrSerotype")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String serovarOrSerotype;
    @XmlElement(name = "Pathovar")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String pathovar;
    @XmlElement(name = "Mutant")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String mutant;
    @XmlElement(name = "Genotype")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String genotype;
    @XmlElement(name = "GrowthConditions")
    protected StringL growthConditions;
    @XmlElement(name = "GrowthConditionAtomised")
    protected CultureCollectionUnit.GrowthConditionAtomised growthConditionAtomised;
    @XmlElement(name = "References")
    protected CultureCollectionUnit.References references;
    @XmlElement(name = "FormOfSupply")
    protected StringL formOfSupply;
    @XmlElement(name = "Applications")
    protected StringL applications;
    @XmlElement(name = "Hazard")
    protected StringL hazard;

    /**
     * Gets the value of the organismType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrganismType() {
        return organismType;
    }

    /**
     * Sets the value of the organismType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrganismType(String value) {
        this.organismType = value;
    }

    /**
     * Gets the value of the infrasubspecificName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInfrasubspecificName() {
        return infrasubspecificName;
    }

    /**
     * Sets the value of the infrasubspecificName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInfrasubspecificName(String value) {
        this.infrasubspecificName = value;
    }

    /**
     * Gets the value of the cultureNames property.
     * 
     * @return
     *     possible object is
     *     {@link CultureCollectionUnit.CultureNames }
     *     
     */
    public CultureCollectionUnit.CultureNames getCultureNames() {
        return cultureNames;
    }

    /**
     * Sets the value of the cultureNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link CultureCollectionUnit.CultureNames }
     *     
     */
    public void setCultureNames(CultureCollectionUnit.CultureNames value) {
        this.cultureNames = value;
    }

    /**
     * Gets the value of the strain property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrain() {
        return strain;
    }

    /**
     * Sets the value of the strain property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrain(String value) {
        this.strain = value;
    }

    /**
     * Gets the value of the serovarOrSerotype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSerovarOrSerotype() {
        return serovarOrSerotype;
    }

    /**
     * Sets the value of the serovarOrSerotype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSerovarOrSerotype(String value) {
        this.serovarOrSerotype = value;
    }

    /**
     * Gets the value of the pathovar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPathovar() {
        return pathovar;
    }

    /**
     * Sets the value of the pathovar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPathovar(String value) {
        this.pathovar = value;
    }

    /**
     * Gets the value of the mutant property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMutant() {
        return mutant;
    }

    /**
     * Sets the value of the mutant property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMutant(String value) {
        this.mutant = value;
    }

    /**
     * Gets the value of the genotype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGenotype() {
        return genotype;
    }

    /**
     * Sets the value of the genotype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGenotype(String value) {
        this.genotype = value;
    }

    /**
     * Gets the value of the growthConditions property.
     * 
     * @return
     *     possible object is
     *     {@link StringL }
     *     
     */
    public StringL getGrowthConditions() {
        return growthConditions;
    }

    /**
     * Sets the value of the growthConditions property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringL }
     *     
     */
    public void setGrowthConditions(StringL value) {
        this.growthConditions = value;
    }

    /**
     * Gets the value of the growthConditionAtomised property.
     * 
     * @return
     *     possible object is
     *     {@link CultureCollectionUnit.GrowthConditionAtomised }
     *     
     */
    public CultureCollectionUnit.GrowthConditionAtomised getGrowthConditionAtomised() {
        return growthConditionAtomised;
    }

    /**
     * Sets the value of the growthConditionAtomised property.
     * 
     * @param value
     *     allowed object is
     *     {@link CultureCollectionUnit.GrowthConditionAtomised }
     *     
     */
    public void setGrowthConditionAtomised(CultureCollectionUnit.GrowthConditionAtomised value) {
        this.growthConditionAtomised = value;
    }

    /**
     * Gets the value of the references property.
     * 
     * @return
     *     possible object is
     *     {@link CultureCollectionUnit.References }
     *     
     */
    public CultureCollectionUnit.References getReferences() {
        return references;
    }

    /**
     * Sets the value of the references property.
     * 
     * @param value
     *     allowed object is
     *     {@link CultureCollectionUnit.References }
     *     
     */
    public void setReferences(CultureCollectionUnit.References value) {
        this.references = value;
    }

    /**
     * Gets the value of the formOfSupply property.
     * 
     * @return
     *     possible object is
     *     {@link StringL }
     *     
     */
    public StringL getFormOfSupply() {
        return formOfSupply;
    }

    /**
     * Sets the value of the formOfSupply property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringL }
     *     
     */
    public void setFormOfSupply(StringL value) {
        this.formOfSupply = value;
    }

    /**
     * Gets the value of the applications property.
     * 
     * @return
     *     possible object is
     *     {@link StringL }
     *     
     */
    public StringL getApplications() {
        return applications;
    }

    /**
     * Sets the value of the applications property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringL }
     *     
     */
    public void setApplications(StringL value) {
        this.applications = value;
    }

    /**
     * Gets the value of the hazard property.
     * 
     * @return
     *     possible object is
     *     {@link StringL }
     *     
     */
    public StringL getHazard() {
        return hazard;
    }

    /**
     * Sets the value of the hazard property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringL }
     *     
     */
    public void setHazard(StringL value) {
        this.hazard = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CultureName" type="{http://www.tdwg.org/schemas/abcd/2.06}StringL" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "cultureName"
    })
    public static class CultureNames {

        @XmlElement(name = "CultureName")
        protected List<StringL> cultureName;

        /**
         * Gets the value of the cultureName property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the cultureName property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCultureName().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link StringL }
         * 
         * 
         */
        public List<StringL> getCultureName() {
            if (cultureName == null) {
                cultureName = new ArrayList<StringL>();
            }
            return this.cultureName;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CultureMedium" type="{http://www.tdwg.org/schemas/abcd/2.06}StringL" minOccurs="0"/>
     *         &lt;element name="Aerobicity" type="{http://www.tdwg.org/schemas/abcd/2.06}StringL" minOccurs="0"/>
     *         &lt;element name="Temperature" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="TemperatureType">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
     *                       &lt;enumeration value="Celsius"/>
     *                       &lt;enumeration value="Fahrenheit"/>
     *                       &lt;enumeration value="Absolute"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *                 &lt;attribute name="scale" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "cultureMedium",
        "aerobicity",
        "temperature"
    })
    public static class GrowthConditionAtomised {

        @XmlElement(name = "CultureMedium")
        protected StringL cultureMedium;
        @XmlElement(name = "Aerobicity")
        protected StringL aerobicity;
        @XmlElement(name = "Temperature")
        protected CultureCollectionUnit.GrowthConditionAtomised.Temperature temperature;

        /**
         * Gets the value of the cultureMedium property.
         * 
         * @return
         *     possible object is
         *     {@link StringL }
         *     
         */
        public StringL getCultureMedium() {
            return cultureMedium;
        }

        /**
         * Sets the value of the cultureMedium property.
         * 
         * @param value
         *     allowed object is
         *     {@link StringL }
         *     
         */
        public void setCultureMedium(StringL value) {
            this.cultureMedium = value;
        }

        /**
         * Gets the value of the aerobicity property.
         * 
         * @return
         *     possible object is
         *     {@link StringL }
         *     
         */
        public StringL getAerobicity() {
            return aerobicity;
        }

        /**
         * Sets the value of the aerobicity property.
         * 
         * @param value
         *     allowed object is
         *     {@link StringL }
         *     
         */
        public void setAerobicity(StringL value) {
            this.aerobicity = value;
        }

        /**
         * Gets the value of the temperature property.
         * 
         * @return
         *     possible object is
         *     {@link CultureCollectionUnit.GrowthConditionAtomised.Temperature }
         *     
         */
        public CultureCollectionUnit.GrowthConditionAtomised.Temperature getTemperature() {
            return temperature;
        }

        /**
         * Sets the value of the temperature property.
         * 
         * @param value
         *     allowed object is
         *     {@link CultureCollectionUnit.GrowthConditionAtomised.Temperature }
         *     
         */
        public void setTemperature(CultureCollectionUnit.GrowthConditionAtomised.Temperature value) {
            this.temperature = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="TemperatureType">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
         *             &lt;enumeration value="Celsius"/>
         *             &lt;enumeration value="Fahrenheit"/>
         *             &lt;enumeration value="Absolute"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *       &lt;attribute name="scale" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Temperature {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "TemperatureType")
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            protected String temperatureType;
            @XmlAttribute(name = "scale")
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlSchemaType(name = "NMTOKEN")
            protected String scale;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the temperatureType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTemperatureType() {
                return temperatureType;
            }

            /**
             * Sets the value of the temperatureType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTemperatureType(String value) {
                this.temperatureType = value;
            }

            /**
             * Gets the value of the scale property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getScale() {
                return scale;
            }

            /**
             * Sets the value of the scale property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setScale(String value) {
                this.scale = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Reference" type="{http://www.tdwg.org/schemas/abcd/2.06}Reference" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "reference"
    })
    public static class References {

        @XmlElement(name = "Reference")
        protected List<Reference> reference;

        /**
         * Gets the value of the reference property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the reference property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getReference().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Reference }
         * 
         * 
         */
        public List<Reference> getReference() {
            if (reference == null) {
                reference = new ArrayList<Reference>();
            }
            return this.reference;
        }

    }

}
