//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.16 at 11:51:40 AM CET 
//


package nl.naturalis.oaipmh.api.jaxb.abcd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Taxon name used to further classify the
 * 				identification result.
 * 			
 * 
 * <p>Java class for HigherTaxon complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HigherTaxon">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="HigherTaxonName" type="{http://www.tdwg.org/schemas/abcd/2.06}Monomial"/>
 *         &lt;element name="HigherTaxonRank" type="{http://www.tdwg.org/schemas/abcd/2.06}HigherTaxonRankEnum" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HigherTaxon", propOrder = {
    "higherTaxonName",
    "higherTaxonRank"
})
public class HigherTaxon {

    @XmlElement(name = "HigherTaxonName", required = true)
    protected String higherTaxonName;
    @XmlElement(name = "HigherTaxonRank")
    @XmlSchemaType(name = "Name")
    protected HigherTaxonRankEnum higherTaxonRank;

    /**
     * Gets the value of the higherTaxonName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHigherTaxonName() {
        return higherTaxonName;
    }

    /**
     * Sets the value of the higherTaxonName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHigherTaxonName(String value) {
        this.higherTaxonName = value;
    }

    /**
     * Gets the value of the higherTaxonRank property.
     * 
     * @return
     *     possible object is
     *     {@link HigherTaxonRankEnum }
     *     
     */
    public HigherTaxonRankEnum getHigherTaxonRank() {
        return higherTaxonRank;
    }

    /**
     * Sets the value of the higherTaxonRank property.
     * 
     * @param value
     *     allowed object is
     *     {@link HigherTaxonRankEnum }
     *     
     */
    public void setHigherTaxonRank(HigherTaxonRankEnum value) {
        this.higherTaxonRank = value;
    }

}
