//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.16 at 11:51:40 AM CET 
//


package nl.naturalis.oaipmh.api.jaxb.abcd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * An atomised scientific name under the International
 * 				Code of Zoological Nomenclature
 * 			
 * 
 * <p>Java class for NameZoological complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NameZoological">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GenusOrMonomial" type="{http://www.tdwg.org/schemas/abcd/2.06}Monomial" minOccurs="0"/>
 *         &lt;element name="Subgenus" type="{http://www.tdwg.org/schemas/abcd/2.06}Monomial" minOccurs="0"/>
 *         &lt;element name="SpeciesEpithet" type="{http://www.tdwg.org/schemas/abcd/2.06}Epithet" minOccurs="0"/>
 *         &lt;element name="SubspeciesEpithet" type="{http://www.tdwg.org/schemas/abcd/2.06}Epithet" minOccurs="0"/>
 *         &lt;element name="AuthorTeamOriginalAndYear" type="{http://www.tdwg.org/schemas/abcd/2.06}String" minOccurs="0"/>
 *         &lt;element name="AuthorTeamParenthesisAndYear" type="{http://www.tdwg.org/schemas/abcd/2.06}String" minOccurs="0"/>
 *         &lt;element name="CombinationAuthorTeamAndYear" type="{http://www.tdwg.org/schemas/abcd/2.06}String" minOccurs="0"/>
 *         &lt;element name="Breed" type="{http://www.tdwg.org/schemas/abcd/2.06}String" minOccurs="0"/>
 *         &lt;element name="NamedIndividual" type="{http://www.tdwg.org/schemas/abcd/2.06}String" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NameZoological", propOrder = {
    "genusOrMonomial",
    "subgenus",
    "speciesEpithet",
    "subspeciesEpithet",
    "authorTeamOriginalAndYear",
    "authorTeamParenthesisAndYear",
    "combinationAuthorTeamAndYear",
    "breed",
    "namedIndividual"
})
public class NameZoological {

    @XmlElement(name = "GenusOrMonomial")
    protected String genusOrMonomial;
    @XmlElement(name = "Subgenus")
    protected String subgenus;
    @XmlElement(name = "SpeciesEpithet")
    protected String speciesEpithet;
    @XmlElement(name = "SubspeciesEpithet")
    protected String subspeciesEpithet;
    @XmlElement(name = "AuthorTeamOriginalAndYear")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String authorTeamOriginalAndYear;
    @XmlElement(name = "AuthorTeamParenthesisAndYear")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String authorTeamParenthesisAndYear;
    @XmlElement(name = "CombinationAuthorTeamAndYear")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String combinationAuthorTeamAndYear;
    @XmlElement(name = "Breed")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String breed;
    @XmlElement(name = "NamedIndividual")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String namedIndividual;

    /**
     * Gets the value of the genusOrMonomial property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGenusOrMonomial() {
        return genusOrMonomial;
    }

    /**
     * Sets the value of the genusOrMonomial property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGenusOrMonomial(String value) {
        this.genusOrMonomial = value;
    }

    /**
     * Gets the value of the subgenus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubgenus() {
        return subgenus;
    }

    /**
     * Sets the value of the subgenus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubgenus(String value) {
        this.subgenus = value;
    }

    /**
     * Gets the value of the speciesEpithet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpeciesEpithet() {
        return speciesEpithet;
    }

    /**
     * Sets the value of the speciesEpithet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpeciesEpithet(String value) {
        this.speciesEpithet = value;
    }

    /**
     * Gets the value of the subspeciesEpithet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubspeciesEpithet() {
        return subspeciesEpithet;
    }

    /**
     * Sets the value of the subspeciesEpithet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubspeciesEpithet(String value) {
        this.subspeciesEpithet = value;
    }

    /**
     * Gets the value of the authorTeamOriginalAndYear property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthorTeamOriginalAndYear() {
        return authorTeamOriginalAndYear;
    }

    /**
     * Sets the value of the authorTeamOriginalAndYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthorTeamOriginalAndYear(String value) {
        this.authorTeamOriginalAndYear = value;
    }

    /**
     * Gets the value of the authorTeamParenthesisAndYear property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthorTeamParenthesisAndYear() {
        return authorTeamParenthesisAndYear;
    }

    /**
     * Sets the value of the authorTeamParenthesisAndYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthorTeamParenthesisAndYear(String value) {
        this.authorTeamParenthesisAndYear = value;
    }

    /**
     * Gets the value of the combinationAuthorTeamAndYear property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCombinationAuthorTeamAndYear() {
        return combinationAuthorTeamAndYear;
    }

    /**
     * Sets the value of the combinationAuthorTeamAndYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCombinationAuthorTeamAndYear(String value) {
        this.combinationAuthorTeamAndYear = value;
    }

    /**
     * Gets the value of the breed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBreed() {
        return breed;
    }

    /**
     * Sets the value of the breed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBreed(String value) {
        this.breed = value;
    }

    /**
     * Gets the value of the namedIndividual property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNamedIndividual() {
        return namedIndividual;
    }

    /**
     * Sets the value of the namedIndividual property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNamedIndividual(String value) {
        this.namedIndividual = value;
    }

}
