//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.16 at 11:51:40 AM CET 
//


package nl.naturalis.oaipmh.api.jaxb.abcd;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the nl.naturalis.oaipmh.api.jaxb.abcd package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _UnitSpecimenUnitAccessionsAccessionDate_QNAME = new QName("http://www.tdwg.org/schemas/abcd/2.06", "AccessionDate");
    private final static QName _UnitSpecimenUnitAccessionsAccessionNumber_QNAME = new QName("http://www.tdwg.org/schemas/abcd/2.06", "AccessionNumber");
    private final static QName _UnitSpecimenUnitAccessionsAccessionCatalogue_QNAME = new QName("http://www.tdwg.org/schemas/abcd/2.06", "AccessionCatalogue");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: nl.naturalis.oaipmh.api.jaxb.abcd
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DataSets }
     * 
     */
    public DataSets createDataSets() {
        return new DataSets();
    }

    /**
     * Create an instance of {@link TaxonIdentified }
     * 
     */
    public TaxonIdentified createTaxonIdentified() {
        return new TaxonIdentified();
    }

    /**
     * Create an instance of {@link NameBotanical }
     * 
     */
    public NameBotanical createNameBotanical() {
        return new NameBotanical();
    }

    /**
     * Create an instance of {@link Contact }
     * 
     */
    public Contact createContact() {
        return new Contact();
    }

    /**
     * Create an instance of {@link IPRStatements }
     * 
     */
    public IPRStatements createIPRStatements() {
        return new IPRStatements();
    }

    /**
     * Create an instance of {@link ScientificName }
     * 
     */
    public ScientificName createScientificName() {
        return new ScientificName();
    }

    /**
     * Create an instance of {@link ScientificNameIdentified }
     * 
     */
    public ScientificNameIdentified createScientificNameIdentified() {
        return new ScientificNameIdentified();
    }

    /**
     * Create an instance of {@link Organisation }
     * 
     */
    public Organisation createOrganisation() {
        return new Organisation();
    }

    /**
     * Create an instance of {@link PersonName }
     * 
     */
    public PersonName createPersonName() {
        return new PersonName();
    }

    /**
     * Create an instance of {@link PalaeontologicalUnit }
     * 
     */
    public PalaeontologicalUnit createPalaeontologicalUnit() {
        return new PalaeontologicalUnit();
    }

    /**
     * Create an instance of {@link Identification }
     * 
     */
    public Identification createIdentification() {
        return new Identification();
    }

    /**
     * Create an instance of {@link Identification.Identifiers }
     * 
     */
    public Identification.Identifiers createIdentificationIdentifiers() {
        return new Identification.Identifiers();
    }

    /**
     * Create an instance of {@link Gathering }
     * 
     */
    public Gathering createGathering() {
        return new Gathering();
    }

    /**
     * Create an instance of {@link Gathering.Synecology }
     * 
     */
    public Gathering.Synecology createGatheringSynecology() {
        return new Gathering.Synecology();
    }

    /**
     * Create an instance of {@link Gathering.Biotope }
     * 
     */
    public Gathering.Biotope createGatheringBiotope() {
        return new Gathering.Biotope();
    }

    /**
     * Create an instance of {@link MeasurementOrFact }
     * 
     */
    public MeasurementOrFact createMeasurementOrFact() {
        return new MeasurementOrFact();
    }

    /**
     * Create an instance of {@link Gathering.SiteCoordinateSets }
     * 
     */
    public Gathering.SiteCoordinateSets createGatheringSiteCoordinateSets() {
        return new Gathering.SiteCoordinateSets();
    }

    /**
     * Create an instance of {@link Gathering.SiteCoordinateSets.SiteCoordinates }
     * 
     */
    public Gathering.SiteCoordinateSets.SiteCoordinates createGatheringSiteCoordinateSetsSiteCoordinates() {
        return new Gathering.SiteCoordinateSets.SiteCoordinates();
    }

    /**
     * Create an instance of {@link Gathering.NearNamedPlaces }
     * 
     */
    public Gathering.NearNamedPlaces createGatheringNearNamedPlaces() {
        return new Gathering.NearNamedPlaces();
    }

    /**
     * Create an instance of {@link Gathering.NamedAreas }
     * 
     */
    public Gathering.NamedAreas createGatheringNamedAreas() {
        return new Gathering.NamedAreas();
    }

    /**
     * Create an instance of {@link Gathering.Agents }
     * 
     */
    public Gathering.Agents createGatheringAgents() {
        return new Gathering.Agents();
    }

    /**
     * Create an instance of {@link ContentMetadata }
     * 
     */
    public ContentMetadata createContentMetadata() {
        return new ContentMetadata();
    }

    /**
     * Create an instance of {@link ContentMetadata.Scope }
     * 
     */
    public ContentMetadata.Scope createContentMetadataScope() {
        return new ContentMetadata.Scope();
    }

    /**
     * Create an instance of {@link Stratigraphy }
     * 
     */
    public Stratigraphy createStratigraphy() {
        return new Stratigraphy();
    }

    /**
     * Create an instance of {@link MultiMediaObject }
     * 
     */
    public MultiMediaObject createMultiMediaObject() {
        return new MultiMediaObject();
    }

    /**
     * Create an instance of {@link PGRUnit }
     * 
     */
    public PGRUnit createPGRUnit() {
        return new PGRUnit();
    }

    /**
     * Create an instance of {@link MycologicalUnit }
     * 
     */
    public MycologicalUnit createMycologicalUnit() {
        return new MycologicalUnit();
    }

    /**
     * Create an instance of {@link Unit }
     * 
     */
    public Unit createUnit() {
        return new Unit();
    }

    /**
     * Create an instance of {@link Unit.EAnnotations }
     * 
     */
    public Unit.EAnnotations createUnitEAnnotations() {
        return new Unit.EAnnotations();
    }

    /**
     * Create an instance of {@link Unit.Assemblages }
     * 
     */
    public Unit.Assemblages createUnitAssemblages() {
        return new Unit.Assemblages();
    }

    /**
     * Create an instance of {@link Unit.Associations }
     * 
     */
    public Unit.Associations createUnitAssociations() {
        return new Unit.Associations();
    }

    /**
     * Create an instance of {@link Unit.ObservationUnit }
     * 
     */
    public Unit.ObservationUnit createUnitObservationUnit() {
        return new Unit.ObservationUnit();
    }

    /**
     * Create an instance of {@link Unit.SpecimenUnit }
     * 
     */
    public Unit.SpecimenUnit createUnitSpecimenUnit() {
        return new Unit.SpecimenUnit();
    }

    /**
     * Create an instance of {@link Unit.SpecimenUnit.NomenclaturalTypeDesignations }
     * 
     */
    public Unit.SpecimenUnit.NomenclaturalTypeDesignations createUnitSpecimenUnitNomenclaturalTypeDesignations() {
        return new Unit.SpecimenUnit.NomenclaturalTypeDesignations();
    }

    /**
     * Create an instance of {@link Unit.SpecimenUnit.History }
     * 
     */
    public Unit.SpecimenUnit.History createUnitSpecimenUnitHistory() {
        return new Unit.SpecimenUnit.History();
    }

    /**
     * Create an instance of {@link Unit.SpecimenUnit.History.PreviousUnits }
     * 
     */
    public Unit.SpecimenUnit.History.PreviousUnits createUnitSpecimenUnitHistoryPreviousUnits() {
        return new Unit.SpecimenUnit.History.PreviousUnits();
    }

    /**
     * Create an instance of {@link Unit.SpecimenUnit.Marks }
     * 
     */
    public Unit.SpecimenUnit.Marks createUnitSpecimenUnitMarks() {
        return new Unit.SpecimenUnit.Marks();
    }

    /**
     * Create an instance of {@link Unit.SpecimenUnit.Marks.Mark }
     * 
     */
    public Unit.SpecimenUnit.Marks.Mark createUnitSpecimenUnitMarksMark() {
        return new Unit.SpecimenUnit.Marks.Mark();
    }

    /**
     * Create an instance of {@link Unit.SpecimenUnit.Preparations }
     * 
     */
    public Unit.SpecimenUnit.Preparations createUnitSpecimenUnitPreparations() {
        return new Unit.SpecimenUnit.Preparations();
    }

    /**
     * Create an instance of {@link Unit.UnitContentContacts }
     * 
     */
    public Unit.UnitContentContacts createUnitUnitContentContacts() {
        return new Unit.UnitContentContacts();
    }

    /**
     * Create an instance of {@link Label }
     * 
     */
    public Label createLabel() {
        return new Label();
    }

    /**
     * Create an instance of {@link ZoologicalUnit }
     * 
     */
    public ZoologicalUnit createZoologicalUnit() {
        return new ZoologicalUnit();
    }

    /**
     * Create an instance of {@link CultureCollectionUnit }
     * 
     */
    public CultureCollectionUnit createCultureCollectionUnit() {
        return new CultureCollectionUnit();
    }

    /**
     * Create an instance of {@link CultureCollectionUnit.GrowthConditionAtomised }
     * 
     */
    public CultureCollectionUnit.GrowthConditionAtomised createCultureCollectionUnitGrowthConditionAtomised() {
        return new CultureCollectionUnit.GrowthConditionAtomised();
    }

    /**
     * Create an instance of {@link DataSets.DataSet }
     * 
     */
    public DataSets.DataSet createDataSetsDataSet() {
        return new DataSets.DataSet();
    }

    /**
     * Create an instance of {@link TelephoneDevice }
     * 
     */
    public TelephoneDevice createTelephoneDevice() {
        return new TelephoneDevice();
    }

    /**
     * Create an instance of {@link TelephoneNumber }
     * 
     */
    public TelephoneNumber createTelephoneNumber() {
        return new TelephoneNumber();
    }

    /**
     * Create an instance of {@link Aspect }
     * 
     */
    public Aspect createAspect() {
        return new Aspect();
    }

    /**
     * Create an instance of {@link DateTime }
     * 
     */
    public DateTime createDateTime() {
        return new DateTime();
    }

    /**
     * Create an instance of {@link MicroAgentP }
     * 
     */
    public MicroAgentP createMicroAgentP() {
        return new MicroAgentP();
    }

    /**
     * Create an instance of {@link Lookup }
     * 
     */
    public Lookup createLookup() {
        return new Lookup();
    }

    /**
     * Create an instance of {@link BotanicalGardenUnit }
     * 
     */
    public BotanicalGardenUnit createBotanicalGardenUnit() {
        return new BotanicalGardenUnit();
    }

    /**
     * Create an instance of {@link Sequence }
     * 
     */
    public Sequence createSequence() {
        return new Sequence();
    }

    /**
     * Create an instance of {@link StringLP }
     * 
     */
    public StringLP createStringLP() {
        return new StringLP();
    }

    /**
     * Create an instance of {@link StringP }
     * 
     */
    public StringP createStringP() {
        return new StringP();
    }

    /**
     * Create an instance of {@link MicroAgent }
     * 
     */
    public MicroAgent createMicroAgent() {
        return new MicroAgent();
    }

    /**
     * Create an instance of {@link AnyUriP }
     * 
     */
    public AnyUriP createAnyUriP() {
        return new AnyUriP();
    }

    /**
     * Create an instance of {@link StringL }
     * 
     */
    public StringL createStringL() {
        return new StringL();
    }

    /**
     * Create an instance of {@link StringP255 }
     * 
     */
    public StringP255 createStringP255() {
        return new StringP255();
    }

    /**
     * Create an instance of {@link Country }
     * 
     */
    public Country createCountry() {
        return new Country();
    }

    /**
     * Create an instance of {@link HigherTaxon }
     * 
     */
    public HigherTaxon createHigherTaxon() {
        return new HigherTaxon();
    }

    /**
     * Create an instance of {@link StringL255 }
     * 
     */
    public StringL255 createStringL255() {
        return new StringL255();
    }

    /**
     * Create an instance of {@link ImageSize }
     * 
     */
    public ImageSize createImageSize() {
        return new ImageSize();
    }

    /**
     * Create an instance of {@link LabelRepr }
     * 
     */
    public LabelRepr createLabelRepr() {
        return new LabelRepr();
    }

    /**
     * Create an instance of {@link LookupL }
     * 
     */
    public LookupL createLookupL() {
        return new LookupL();
    }

    /**
     * Create an instance of {@link NameZoological }
     * 
     */
    public NameZoological createNameZoological() {
        return new NameZoological();
    }

    /**
     * Create an instance of {@link Statement }
     * 
     */
    public Statement createStatement() {
        return new Statement();
    }

    /**
     * Create an instance of {@link Reference }
     * 
     */
    public Reference createReference() {
        return new Reference();
    }

    /**
     * Create an instance of {@link NameViral }
     * 
     */
    public NameViral createNameViral() {
        return new NameViral();
    }

    /**
     * Create an instance of {@link NameBacterial }
     * 
     */
    public NameBacterial createNameBacterial() {
        return new NameBacterial();
    }

    /**
     * Create an instance of {@link nl.naturalis.oaipmh.api.jaxb.abcd.NamedArea }
     * 
     */
    public nl.naturalis.oaipmh.api.jaxb.abcd.NamedArea createNamedArea() {
        return new nl.naturalis.oaipmh.api.jaxb.abcd.NamedArea();
    }

    /**
     * Create an instance of {@link HerbariumUnit }
     * 
     */
    public HerbariumUnit createHerbariumUnit() {
        return new HerbariumUnit();
    }

    /**
     * Create an instance of {@link MetadataDescriptionRepr }
     * 
     */
    public MetadataDescriptionRepr createMetadataDescriptionRepr() {
        return new MetadataDescriptionRepr();
    }

    /**
     * Create an instance of {@link StringLP255 }
     * 
     */
    public StringLP255 createStringLP255() {
        return new StringLP255();
    }

    /**
     * Create an instance of {@link RevisionData }
     * 
     */
    public RevisionData createRevisionData() {
        return new RevisionData();
    }

    /**
     * Create an instance of {@link TaxonIdentified.HigherTaxa }
     * 
     */
    public TaxonIdentified.HigherTaxa createTaxonIdentifiedHigherTaxa() {
        return new TaxonIdentified.HigherTaxa();
    }

    /**
     * Create an instance of {@link NameBotanical.HybridFlag }
     * 
     */
    public NameBotanical.HybridFlag createNameBotanicalHybridFlag() {
        return new NameBotanical.HybridFlag();
    }

    /**
     * Create an instance of {@link NameBotanical.TradeDesignationNames }
     * 
     */
    public NameBotanical.TradeDesignationNames createNameBotanicalTradeDesignationNames() {
        return new NameBotanical.TradeDesignationNames();
    }

    /**
     * Create an instance of {@link Contact.Roles }
     * 
     */
    public Contact.Roles createContactRoles() {
        return new Contact.Roles();
    }

    /**
     * Create an instance of {@link Contact.Addresses }
     * 
     */
    public Contact.Addresses createContactAddresses() {
        return new Contact.Addresses();
    }

    /**
     * Create an instance of {@link Contact.TelephoneNumbers }
     * 
     */
    public Contact.TelephoneNumbers createContactTelephoneNumbers() {
        return new Contact.TelephoneNumbers();
    }

    /**
     * Create an instance of {@link Contact.EmailAddresses }
     * 
     */
    public Contact.EmailAddresses createContactEmailAddresses() {
        return new Contact.EmailAddresses();
    }

    /**
     * Create an instance of {@link Contact.URIs }
     * 
     */
    public Contact.URIs createContactURIs() {
        return new Contact.URIs();
    }

    /**
     * Create an instance of {@link IPRStatements.IPRDeclarations }
     * 
     */
    public IPRStatements.IPRDeclarations createIPRStatementsIPRDeclarations() {
        return new IPRStatements.IPRDeclarations();
    }

    /**
     * Create an instance of {@link IPRStatements.Copyrights }
     * 
     */
    public IPRStatements.Copyrights createIPRStatementsCopyrights() {
        return new IPRStatements.Copyrights();
    }

    /**
     * Create an instance of {@link IPRStatements.Licenses }
     * 
     */
    public IPRStatements.Licenses createIPRStatementsLicenses() {
        return new IPRStatements.Licenses();
    }

    /**
     * Create an instance of {@link IPRStatements.TermsOfUseStatements }
     * 
     */
    public IPRStatements.TermsOfUseStatements createIPRStatementsTermsOfUseStatements() {
        return new IPRStatements.TermsOfUseStatements();
    }

    /**
     * Create an instance of {@link IPRStatements.Disclaimers }
     * 
     */
    public IPRStatements.Disclaimers createIPRStatementsDisclaimers() {
        return new IPRStatements.Disclaimers();
    }

    /**
     * Create an instance of {@link IPRStatements.Acknowledgements }
     * 
     */
    public IPRStatements.Acknowledgements createIPRStatementsAcknowledgements() {
        return new IPRStatements.Acknowledgements();
    }

    /**
     * Create an instance of {@link IPRStatements.Citations }
     * 
     */
    public IPRStatements.Citations createIPRStatementsCitations() {
        return new IPRStatements.Citations();
    }

    /**
     * Create an instance of {@link ScientificName.NameAtomised }
     * 
     */
    public ScientificName.NameAtomised createScientificNameNameAtomised() {
        return new ScientificName.NameAtomised();
    }

    /**
     * Create an instance of {@link ScientificNameIdentified.IdentificationQualifier }
     * 
     */
    public ScientificNameIdentified.IdentificationQualifier createScientificNameIdentifiedIdentificationQualifier() {
        return new ScientificNameIdentified.IdentificationQualifier();
    }

    /**
     * Create an instance of {@link Organisation.OrgUnits }
     * 
     */
    public Organisation.OrgUnits createOrganisationOrgUnits() {
        return new Organisation.OrgUnits();
    }

    /**
     * Create an instance of {@link PersonName.AtomisedName }
     * 
     */
    public PersonName.AtomisedName createPersonNameAtomisedName() {
        return new PersonName.AtomisedName();
    }

    /**
     * Create an instance of {@link PalaeontologicalUnit.Preservation }
     * 
     */
    public PalaeontologicalUnit.Preservation createPalaeontologicalUnitPreservation() {
        return new PalaeontologicalUnit.Preservation();
    }

    /**
     * Create an instance of {@link Identification.Result }
     * 
     */
    public Identification.Result createIdentificationResult() {
        return new Identification.Result();
    }

    /**
     * Create an instance of {@link Identification.References }
     * 
     */
    public Identification.References createIdentificationReferences() {
        return new Identification.References();
    }

    /**
     * Create an instance of {@link Identification.Identifiers.Identifier }
     * 
     */
    public Identification.Identifiers.Identifier createIdentificationIdentifiersIdentifier() {
        return new Identification.Identifiers.Identifier();
    }

    /**
     * Create an instance of {@link Gathering.Permits }
     * 
     */
    public Gathering.Permits createGatheringPermits() {
        return new Gathering.Permits();
    }

    /**
     * Create an instance of {@link Gathering.Project }
     * 
     */
    public Gathering.Project createGatheringProject() {
        return new Gathering.Project();
    }

    /**
     * Create an instance of {@link Gathering.Depth }
     * 
     */
    public Gathering.Depth createGatheringDepth() {
        return new Gathering.Depth();
    }

    /**
     * Create an instance of {@link Gathering.Height }
     * 
     */
    public Gathering.Height createGatheringHeight() {
        return new Gathering.Height();
    }

    /**
     * Create an instance of {@link Gathering.SiteMeasurementsOrFacts }
     * 
     */
    public Gathering.SiteMeasurementsOrFacts createGatheringSiteMeasurementsOrFacts() {
        return new Gathering.SiteMeasurementsOrFacts();
    }

    /**
     * Create an instance of {@link Gathering.SiteImages }
     * 
     */
    public Gathering.SiteImages createGatheringSiteImages() {
        return new Gathering.SiteImages();
    }

    /**
     * Create an instance of {@link Gathering.Synecology.AssociatedTaxa }
     * 
     */
    public Gathering.Synecology.AssociatedTaxa createGatheringSynecologyAssociatedTaxa() {
        return new Gathering.Synecology.AssociatedTaxa();
    }

    /**
     * Create an instance of {@link Gathering.Biotope.MeasurementsOrFacts }
     * 
     */
    public Gathering.Biotope.MeasurementsOrFacts createGatheringBiotopeMeasurementsOrFacts() {
        return new Gathering.Biotope.MeasurementsOrFacts();
    }

    /**
     * Create an instance of {@link MeasurementOrFact.MeasurementOrFactAtomised }
     * 
     */
    public MeasurementOrFact.MeasurementOrFactAtomised createMeasurementOrFactMeasurementOrFactAtomised() {
        return new MeasurementOrFact.MeasurementOrFactAtomised();
    }

    /**
     * Create an instance of {@link Gathering.SiteCoordinateSets.SiteCoordinates.CoordinatesUTM }
     * 
     */
    public Gathering.SiteCoordinateSets.SiteCoordinates.CoordinatesUTM createGatheringSiteCoordinateSetsSiteCoordinatesCoordinatesUTM() {
        return new Gathering.SiteCoordinateSets.SiteCoordinates.CoordinatesUTM();
    }

    /**
     * Create an instance of {@link Gathering.SiteCoordinateSets.SiteCoordinates.CoordinatesGrid }
     * 
     */
    public Gathering.SiteCoordinateSets.SiteCoordinates.CoordinatesGrid createGatheringSiteCoordinateSetsSiteCoordinatesCoordinatesGrid() {
        return new Gathering.SiteCoordinateSets.SiteCoordinates.CoordinatesGrid();
    }

    /**
     * Create an instance of {@link Gathering.SiteCoordinateSets.SiteCoordinates.CoordinatesLatLong }
     * 
     */
    public Gathering.SiteCoordinateSets.SiteCoordinates.CoordinatesLatLong createGatheringSiteCoordinateSetsSiteCoordinatesCoordinatesLatLong() {
        return new Gathering.SiteCoordinateSets.SiteCoordinates.CoordinatesLatLong();
    }

    /**
     * Create an instance of {@link Gathering.NearNamedPlaces.NamedPlaceRelation }
     * 
     */
    public Gathering.NearNamedPlaces.NamedPlaceRelation createGatheringNearNamedPlacesNamedPlaceRelation() {
        return new Gathering.NearNamedPlaces.NamedPlaceRelation();
    }

    /**
     * Create an instance of {@link Gathering.NamedAreas.NamedArea }
     * 
     */
    public Gathering.NamedAreas.NamedArea createGatheringNamedAreasNamedArea() {
        return new Gathering.NamedAreas.NamedArea();
    }

    /**
     * Create an instance of {@link Gathering.Agents.GatheringAgent }
     * 
     */
    public Gathering.Agents.GatheringAgent createGatheringAgentsGatheringAgent() {
        return new Gathering.Agents.GatheringAgent();
    }

    /**
     * Create an instance of {@link ContentMetadata.Description }
     * 
     */
    public ContentMetadata.Description createContentMetadataDescription() {
        return new ContentMetadata.Description();
    }

    /**
     * Create an instance of {@link ContentMetadata.Version }
     * 
     */
    public ContentMetadata.Version createContentMetadataVersion() {
        return new ContentMetadata.Version();
    }

    /**
     * Create an instance of {@link ContentMetadata.Owners }
     * 
     */
    public ContentMetadata.Owners createContentMetadataOwners() {
        return new ContentMetadata.Owners();
    }

    /**
     * Create an instance of {@link ContentMetadata.Scope.GeoecologicalTerms }
     * 
     */
    public ContentMetadata.Scope.GeoecologicalTerms createContentMetadataScopeGeoecologicalTerms() {
        return new ContentMetadata.Scope.GeoecologicalTerms();
    }

    /**
     * Create an instance of {@link ContentMetadata.Scope.TaxonomicTerms }
     * 
     */
    public ContentMetadata.Scope.TaxonomicTerms createContentMetadataScopeTaxonomicTerms() {
        return new ContentMetadata.Scope.TaxonomicTerms();
    }

    /**
     * Create an instance of {@link Stratigraphy.ChronostratigraphicTerms }
     * 
     */
    public Stratigraphy.ChronostratigraphicTerms createStratigraphyChronostratigraphicTerms() {
        return new Stratigraphy.ChronostratigraphicTerms();
    }

    /**
     * Create an instance of {@link Stratigraphy.BiostratigraphicTerms }
     * 
     */
    public Stratigraphy.BiostratigraphicTerms createStratigraphyBiostratigraphicTerms() {
        return new Stratigraphy.BiostratigraphicTerms();
    }

    /**
     * Create an instance of {@link Stratigraphy.LithostratigraphicTerms }
     * 
     */
    public Stratigraphy.LithostratigraphicTerms createStratigraphyLithostratigraphicTerms() {
        return new Stratigraphy.LithostratigraphicTerms();
    }

    /**
     * Create an instance of {@link MultiMediaObject.ImageColorSpace }
     * 
     */
    public MultiMediaObject.ImageColorSpace createMultiMediaObjectImageColorSpace() {
        return new MultiMediaObject.ImageColorSpace();
    }

    /**
     * Create an instance of {@link PGRUnit.AccessionNames }
     * 
     */
    public PGRUnit.AccessionNames createPGRUnitAccessionNames() {
        return new PGRUnit.AccessionNames();
    }

    /**
     * Create an instance of {@link MycologicalUnit.MycologicalLiveStages }
     * 
     */
    public MycologicalUnit.MycologicalLiveStages createMycologicalUnitMycologicalLiveStages() {
        return new MycologicalUnit.MycologicalLiveStages();
    }

    /**
     * Create an instance of {@link Unit.UnitReferences }
     * 
     */
    public Unit.UnitReferences createUnitUnitReferences() {
        return new Unit.UnitReferences();
    }

    /**
     * Create an instance of {@link Unit.Identifications }
     * 
     */
    public Unit.Identifications createUnitIdentifications() {
        return new Unit.Identifications();
    }

    /**
     * Create an instance of {@link Unit.MultiMediaObjects }
     * 
     */
    public Unit.MultiMediaObjects createUnitMultiMediaObjects() {
        return new Unit.MultiMediaObjects();
    }

    /**
     * Create an instance of {@link Unit.NamedCollectionsOrSurveys }
     * 
     */
    public Unit.NamedCollectionsOrSurveys createUnitNamedCollectionsOrSurveys() {
        return new Unit.NamedCollectionsOrSurveys();
    }

    /**
     * Create an instance of {@link Unit.MeasurementsOrFacts }
     * 
     */
    public Unit.MeasurementsOrFacts createUnitMeasurementsOrFacts() {
        return new Unit.MeasurementsOrFacts();
    }

    /**
     * Create an instance of {@link Unit.Sequences }
     * 
     */
    public Unit.Sequences createUnitSequences() {
        return new Unit.Sequences();
    }

    /**
     * Create an instance of {@link Unit.EAnnotations.Annotation }
     * 
     */
    public Unit.EAnnotations.Annotation createUnitEAnnotationsAnnotation() {
        return new Unit.EAnnotations.Annotation();
    }

    /**
     * Create an instance of {@link Unit.Assemblages.UnitAssemblage }
     * 
     */
    public Unit.Assemblages.UnitAssemblage createUnitAssemblagesUnitAssemblage() {
        return new Unit.Assemblages.UnitAssemblage();
    }

    /**
     * Create an instance of {@link Unit.Associations.UnitAssociation }
     * 
     */
    public Unit.Associations.UnitAssociation createUnitAssociationsUnitAssociation() {
        return new Unit.Associations.UnitAssociation();
    }

    /**
     * Create an instance of {@link Unit.ObservationUnit.ObservationUnitIdentifiers }
     * 
     */
    public Unit.ObservationUnit.ObservationUnitIdentifiers createUnitObservationUnitObservationUnitIdentifiers() {
        return new Unit.ObservationUnit.ObservationUnitIdentifiers();
    }

    /**
     * Create an instance of {@link Unit.SpecimenUnit.Acquisition }
     * 
     */
    public Unit.SpecimenUnit.Acquisition createUnitSpecimenUnitAcquisition() {
        return new Unit.SpecimenUnit.Acquisition();
    }

    /**
     * Create an instance of {@link Unit.SpecimenUnit.Accessions }
     * 
     */
    public Unit.SpecimenUnit.Accessions createUnitSpecimenUnitAccessions() {
        return new Unit.SpecimenUnit.Accessions();
    }

    /**
     * Create an instance of {@link Unit.SpecimenUnit.NomenclaturalTypeDesignations.NomenclaturalTypeDesignation }
     * 
     */
    public Unit.SpecimenUnit.NomenclaturalTypeDesignations.NomenclaturalTypeDesignation createUnitSpecimenUnitNomenclaturalTypeDesignationsNomenclaturalTypeDesignation() {
        return new Unit.SpecimenUnit.NomenclaturalTypeDesignations.NomenclaturalTypeDesignation();
    }

    /**
     * Create an instance of {@link Unit.SpecimenUnit.History.PreviousUnits.PreviousUnit }
     * 
     */
    public Unit.SpecimenUnit.History.PreviousUnits.PreviousUnit createUnitSpecimenUnitHistoryPreviousUnitsPreviousUnit() {
        return new Unit.SpecimenUnit.History.PreviousUnits.PreviousUnit();
    }

    /**
     * Create an instance of {@link Unit.SpecimenUnit.Marks.Mark.Images }
     * 
     */
    public Unit.SpecimenUnit.Marks.Mark.Images createUnitSpecimenUnitMarksMarkImages() {
        return new Unit.SpecimenUnit.Marks.Mark.Images();
    }

    /**
     * Create an instance of {@link Unit.SpecimenUnit.Preparations.Preparation }
     * 
     */
    public Unit.SpecimenUnit.Preparations.Preparation createUnitSpecimenUnitPreparationsPreparation() {
        return new Unit.SpecimenUnit.Preparations.Preparation();
    }

    /**
     * Create an instance of {@link Unit.UnitContentContacts.UnitContentContact }
     * 
     */
    public Unit.UnitContentContacts.UnitContentContact createUnitUnitContentContactsUnitContentContact() {
        return new Unit.UnitContentContacts.UnitContentContact();
    }

    /**
     * Create an instance of {@link Label.Representation }
     * 
     */
    public Label.Representation createLabelRepresentation() {
        return new Label.Representation();
    }

    /**
     * Create an instance of {@link ZoologicalUnit.PhasesOrStages }
     * 
     */
    public ZoologicalUnit.PhasesOrStages createZoologicalUnitPhasesOrStages() {
        return new ZoologicalUnit.PhasesOrStages();
    }

    /**
     * Create an instance of {@link CultureCollectionUnit.CultureNames }
     * 
     */
    public CultureCollectionUnit.CultureNames createCultureCollectionUnitCultureNames() {
        return new CultureCollectionUnit.CultureNames();
    }

    /**
     * Create an instance of {@link CultureCollectionUnit.References }
     * 
     */
    public CultureCollectionUnit.References createCultureCollectionUnitReferences() {
        return new CultureCollectionUnit.References();
    }

    /**
     * Create an instance of {@link CultureCollectionUnit.GrowthConditionAtomised.Temperature }
     * 
     */
    public CultureCollectionUnit.GrowthConditionAtomised.Temperature createCultureCollectionUnitGrowthConditionAtomisedTemperature() {
        return new CultureCollectionUnit.GrowthConditionAtomised.Temperature();
    }

    /**
     * Create an instance of {@link DataSets.DataSet.TechnicalContacts }
     * 
     */
    public DataSets.DataSet.TechnicalContacts createDataSetsDataSetTechnicalContacts() {
        return new DataSets.DataSet.TechnicalContacts();
    }

    /**
     * Create an instance of {@link DataSets.DataSet.ContentContacts }
     * 
     */
    public DataSets.DataSet.ContentContacts createDataSetsDataSetContentContacts() {
        return new DataSets.DataSet.ContentContacts();
    }

    /**
     * Create an instance of {@link DataSets.DataSet.OtherProviders }
     * 
     */
    public DataSets.DataSet.OtherProviders createDataSetsDataSetOtherProviders() {
        return new DataSets.DataSet.OtherProviders();
    }

    /**
     * Create an instance of {@link DataSets.DataSet.Units }
     * 
     */
    public DataSets.DataSet.Units createDataSetsDataSetUnits() {
        return new DataSets.DataSet.Units();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tdwg.org/schemas/abcd/2.06", name = "AccessionDate", scope = Unit.SpecimenUnit.Accessions.class)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createUnitSpecimenUnitAccessionsAccessionDate(String value) {
        return new JAXBElement<String>(_UnitSpecimenUnitAccessionsAccessionDate_QNAME, String.class, Unit.SpecimenUnit.Accessions.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tdwg.org/schemas/abcd/2.06", name = "AccessionNumber", scope = Unit.SpecimenUnit.Accessions.class)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createUnitSpecimenUnitAccessionsAccessionNumber(String value) {
        return new JAXBElement<String>(_UnitSpecimenUnitAccessionsAccessionNumber_QNAME, String.class, Unit.SpecimenUnit.Accessions.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tdwg.org/schemas/abcd/2.06", name = "AccessionCatalogue", scope = Unit.SpecimenUnit.Accessions.class)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createUnitSpecimenUnitAccessionsAccessionCatalogue(String value) {
        return new JAXBElement<String>(_UnitSpecimenUnitAccessionsAccessionCatalogue_QNAME, String.class, Unit.SpecimenUnit.Accessions.class, value);
    }

}
