//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.16 at 11:51:40 AM CET 
//


package nl.naturalis.oaipmh.api.jaxb.abcd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Name of the taxon identified, formed according to
 * 				the different Codes of Nomenclature which apply to scientific names.
 * 			
 * 
 * <p>Java class for ScientificName complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ScientificName">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FullScientificNameString" type="{http://www.tdwg.org/schemas/abcd/2.06}String"/>
 *         &lt;element name="NameAtomised" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="Bacterial" type="{http://www.tdwg.org/schemas/abcd/2.06}NameBacterial" minOccurs="0"/>
 *                   &lt;element name="Botanical" type="{http://www.tdwg.org/schemas/abcd/2.06}NameBotanical" minOccurs="0"/>
 *                   &lt;element name="Zoological" type="{http://www.tdwg.org/schemas/abcd/2.06}NameZoological" minOccurs="0"/>
 *                   &lt;element name="Viral" type="{http://www.tdwg.org/schemas/abcd/2.06}NameViral" minOccurs="0"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ScientificName", propOrder = {
    "fullScientificNameString",
    "nameAtomised"
})
@XmlSeeAlso({
    ScientificNameIdentified.class
})
public class ScientificName {

    @XmlElement(name = "FullScientificNameString", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String fullScientificNameString;
    @XmlElement(name = "NameAtomised")
    protected ScientificName.NameAtomised nameAtomised;

    /**
     * Gets the value of the fullScientificNameString property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFullScientificNameString() {
        return fullScientificNameString;
    }

    /**
     * Sets the value of the fullScientificNameString property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFullScientificNameString(String value) {
        this.fullScientificNameString = value;
    }

    /**
     * Gets the value of the nameAtomised property.
     * 
     * @return
     *     possible object is
     *     {@link ScientificName.NameAtomised }
     *     
     */
    public ScientificName.NameAtomised getNameAtomised() {
        return nameAtomised;
    }

    /**
     * Sets the value of the nameAtomised property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScientificName.NameAtomised }
     *     
     */
    public void setNameAtomised(ScientificName.NameAtomised value) {
        this.nameAtomised = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="Bacterial" type="{http://www.tdwg.org/schemas/abcd/2.06}NameBacterial" minOccurs="0"/>
     *         &lt;element name="Botanical" type="{http://www.tdwg.org/schemas/abcd/2.06}NameBotanical" minOccurs="0"/>
     *         &lt;element name="Zoological" type="{http://www.tdwg.org/schemas/abcd/2.06}NameZoological" minOccurs="0"/>
     *         &lt;element name="Viral" type="{http://www.tdwg.org/schemas/abcd/2.06}NameViral" minOccurs="0"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "bacterial",
        "botanical",
        "zoological",
        "viral"
    })
    public static class NameAtomised {

        @XmlElement(name = "Bacterial")
        protected NameBacterial bacterial;
        @XmlElement(name = "Botanical")
        protected NameBotanical botanical;
        @XmlElement(name = "Zoological")
        protected NameZoological zoological;
        @XmlElement(name = "Viral")
        protected NameViral viral;

        /**
         * Gets the value of the bacterial property.
         * 
         * @return
         *     possible object is
         *     {@link NameBacterial }
         *     
         */
        public NameBacterial getBacterial() {
            return bacterial;
        }

        /**
         * Sets the value of the bacterial property.
         * 
         * @param value
         *     allowed object is
         *     {@link NameBacterial }
         *     
         */
        public void setBacterial(NameBacterial value) {
            this.bacterial = value;
        }

        /**
         * Gets the value of the botanical property.
         * 
         * @return
         *     possible object is
         *     {@link NameBotanical }
         *     
         */
        public NameBotanical getBotanical() {
            return botanical;
        }

        /**
         * Sets the value of the botanical property.
         * 
         * @param value
         *     allowed object is
         *     {@link NameBotanical }
         *     
         */
        public void setBotanical(NameBotanical value) {
            this.botanical = value;
        }

        /**
         * Gets the value of the zoological property.
         * 
         * @return
         *     possible object is
         *     {@link NameZoological }
         *     
         */
        public NameZoological getZoological() {
            return zoological;
        }

        /**
         * Sets the value of the zoological property.
         * 
         * @param value
         *     allowed object is
         *     {@link NameZoological }
         *     
         */
        public void setZoological(NameZoological value) {
            this.zoological = value;
        }

        /**
         * Gets the value of the viral property.
         * 
         * @return
         *     possible object is
         *     {@link NameViral }
         *     
         */
        public NameViral getViral() {
            return viral;
        }

        /**
         * Sets the value of the viral property.
         * 
         * @param value
         *     allowed object is
         *     {@link NameViral }
         *     
         */
        public void setViral(NameViral value) {
            this.viral = value;
        }

    }

}
