//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2015.12.24 at 09:46:24 AM CET
//
/**
 * JAXB classes generated from the LIMS2 XML schema.
 */
@javax.xml.bind.annotation.XmlSchema(namespace = "http://data.naturalis.nl/geneious",
		xmlns = @XmlNs(namespaceURI = "http://data.naturalis.nl/geneious", prefix = "geneious"),
		elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package nl.naturalis.oaipmh.geneious.jaxb;

import javax.xml.bind.annotation.XmlNs;