//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.15 at 02:41:39 PM CET 
//


package nl.naturalis.lims2.oaipmh.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the nl.naturalis.lims2.oaipmh.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: nl.naturalis.lims2.oaipmh.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Geneious }
     * 
     */
    public Geneious createGeneious() {
        return new Geneious();
    }

    /**
     * Create an instance of {@link Specimen }
     * 
     */
    public Specimen createSpecimen() {
        return new Specimen();
    }

    /**
     * Create an instance of {@link DnaExtractPlate }
     * 
     */
    public DnaExtractPlate createDnaExtractPlate() {
        return new DnaExtractPlate();
    }

    /**
     * Create an instance of {@link DnaExtract }
     * 
     */
    public DnaExtract createDnaExtract() {
        return new DnaExtract();
    }

    /**
     * Create an instance of {@link Amplification }
     * 
     */
    public Amplification createAmplification() {
        return new Amplification();
    }

    /**
     * Create an instance of {@link Sequencing }
     * 
     */
    public Sequencing createSequencing() {
        return new Sequencing();
    }

    /**
     * Create an instance of {@link ExtractPlateUnit }
     * 
     */
    public ExtractPlateUnit createExtractPlateUnit() {
        return new ExtractPlateUnit();
    }

    /**
     * Create an instance of {@link GeneticAccession }
     * 
     */
    public GeneticAccession createGeneticAccession() {
        return new GeneticAccession();
    }

    /**
     * Create an instance of {@link SpecimenUnit }
     * 
     */
    public SpecimenUnit createSpecimenUnit() {
        return new SpecimenUnit();
    }

    /**
     * Create an instance of {@link DnaLabProject }
     * 
     */
    public DnaLabProject createDnaLabProject() {
        return new DnaLabProject();
    }

    /**
     * Create an instance of {@link ExtractUnit }
     * 
     */
    public ExtractUnit createExtractUnit() {
        return new ExtractUnit();
    }

}
