//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.16 at 11:51:40 AM CET 
//


package nl.naturalis.oaipmh.api.jaxb.abcd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A sequence of statements related to Intellectual
 * 				Property Rights, credit and acknoledgement.
 * 			
 * 
 * <p>Java class for IPRStatements complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IPRStatements">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IPRDeclarations" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="IPRDeclaration" type="{http://www.tdwg.org/schemas/abcd/2.06}Statement" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Copyrights" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Copyright" type="{http://www.tdwg.org/schemas/abcd/2.06}Statement" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Licenses" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="License" type="{http://www.tdwg.org/schemas/abcd/2.06}Statement" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="TermsOfUseStatements" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="TermsOfUse" type="{http://www.tdwg.org/schemas/abcd/2.06}Statement" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Disclaimers" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Disclaimer" type="{http://www.tdwg.org/schemas/abcd/2.06}Statement" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Acknowledgements" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Acknowledgement" type="{http://www.tdwg.org/schemas/abcd/2.06}Statement" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Citations" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Citation" type="{http://www.tdwg.org/schemas/abcd/2.06}Statement" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IPRStatements", propOrder = {
    "iprDeclarations",
    "copyrights",
    "licenses",
    "termsOfUseStatements",
    "disclaimers",
    "acknowledgements",
    "citations"
})
public class IPRStatements {

    @XmlElement(name = "IPRDeclarations")
    protected IPRStatements.IPRDeclarations iprDeclarations;
    @XmlElement(name = "Copyrights")
    protected IPRStatements.Copyrights copyrights;
    @XmlElement(name = "Licenses")
    protected IPRStatements.Licenses licenses;
    @XmlElement(name = "TermsOfUseStatements")
    protected IPRStatements.TermsOfUseStatements termsOfUseStatements;
    @XmlElement(name = "Disclaimers")
    protected IPRStatements.Disclaimers disclaimers;
    @XmlElement(name = "Acknowledgements")
    protected IPRStatements.Acknowledgements acknowledgements;
    @XmlElement(name = "Citations")
    protected IPRStatements.Citations citations;

    /**
     * Gets the value of the iprDeclarations property.
     * 
     * @return
     *     possible object is
     *     {@link IPRStatements.IPRDeclarations }
     *     
     */
    public IPRStatements.IPRDeclarations getIPRDeclarations() {
        return iprDeclarations;
    }

    /**
     * Sets the value of the iprDeclarations property.
     * 
     * @param value
     *     allowed object is
     *     {@link IPRStatements.IPRDeclarations }
     *     
     */
    public void setIPRDeclarations(IPRStatements.IPRDeclarations value) {
        this.iprDeclarations = value;
    }

    /**
     * Gets the value of the copyrights property.
     * 
     * @return
     *     possible object is
     *     {@link IPRStatements.Copyrights }
     *     
     */
    public IPRStatements.Copyrights getCopyrights() {
        return copyrights;
    }

    /**
     * Sets the value of the copyrights property.
     * 
     * @param value
     *     allowed object is
     *     {@link IPRStatements.Copyrights }
     *     
     */
    public void setCopyrights(IPRStatements.Copyrights value) {
        this.copyrights = value;
    }

    /**
     * Gets the value of the licenses property.
     * 
     * @return
     *     possible object is
     *     {@link IPRStatements.Licenses }
     *     
     */
    public IPRStatements.Licenses getLicenses() {
        return licenses;
    }

    /**
     * Sets the value of the licenses property.
     * 
     * @param value
     *     allowed object is
     *     {@link IPRStatements.Licenses }
     *     
     */
    public void setLicenses(IPRStatements.Licenses value) {
        this.licenses = value;
    }

    /**
     * Gets the value of the termsOfUseStatements property.
     * 
     * @return
     *     possible object is
     *     {@link IPRStatements.TermsOfUseStatements }
     *     
     */
    public IPRStatements.TermsOfUseStatements getTermsOfUseStatements() {
        return termsOfUseStatements;
    }

    /**
     * Sets the value of the termsOfUseStatements property.
     * 
     * @param value
     *     allowed object is
     *     {@link IPRStatements.TermsOfUseStatements }
     *     
     */
    public void setTermsOfUseStatements(IPRStatements.TermsOfUseStatements value) {
        this.termsOfUseStatements = value;
    }

    /**
     * Gets the value of the disclaimers property.
     * 
     * @return
     *     possible object is
     *     {@link IPRStatements.Disclaimers }
     *     
     */
    public IPRStatements.Disclaimers getDisclaimers() {
        return disclaimers;
    }

    /**
     * Sets the value of the disclaimers property.
     * 
     * @param value
     *     allowed object is
     *     {@link IPRStatements.Disclaimers }
     *     
     */
    public void setDisclaimers(IPRStatements.Disclaimers value) {
        this.disclaimers = value;
    }

    /**
     * Gets the value of the acknowledgements property.
     * 
     * @return
     *     possible object is
     *     {@link IPRStatements.Acknowledgements }
     *     
     */
    public IPRStatements.Acknowledgements getAcknowledgements() {
        return acknowledgements;
    }

    /**
     * Sets the value of the acknowledgements property.
     * 
     * @param value
     *     allowed object is
     *     {@link IPRStatements.Acknowledgements }
     *     
     */
    public void setAcknowledgements(IPRStatements.Acknowledgements value) {
        this.acknowledgements = value;
    }

    /**
     * Gets the value of the citations property.
     * 
     * @return
     *     possible object is
     *     {@link IPRStatements.Citations }
     *     
     */
    public IPRStatements.Citations getCitations() {
        return citations;
    }

    /**
     * Sets the value of the citations property.
     * 
     * @param value
     *     allowed object is
     *     {@link IPRStatements.Citations }
     *     
     */
    public void setCitations(IPRStatements.Citations value) {
        this.citations = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Acknowledgement" type="{http://www.tdwg.org/schemas/abcd/2.06}Statement" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "acknowledgement"
    })
    public static class Acknowledgements {

        @XmlElement(name = "Acknowledgement", required = true)
        protected List<Statement> acknowledgement;

        /**
         * Gets the value of the acknowledgement property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the acknowledgement property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAcknowledgement().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Statement }
         * 
         * 
         */
        public List<Statement> getAcknowledgement() {
            if (acknowledgement == null) {
                acknowledgement = new ArrayList<Statement>();
            }
            return this.acknowledgement;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Citation" type="{http://www.tdwg.org/schemas/abcd/2.06}Statement" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "citation"
    })
    public static class Citations {

        @XmlElement(name = "Citation", required = true)
        protected List<Statement> citation;

        /**
         * Gets the value of the citation property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the citation property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCitation().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Statement }
         * 
         * 
         */
        public List<Statement> getCitation() {
            if (citation == null) {
                citation = new ArrayList<Statement>();
            }
            return this.citation;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Copyright" type="{http://www.tdwg.org/schemas/abcd/2.06}Statement" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "copyright"
    })
    public static class Copyrights {

        @XmlElement(name = "Copyright", required = true)
        protected List<Statement> copyright;

        /**
         * Gets the value of the copyright property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the copyright property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCopyright().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Statement }
         * 
         * 
         */
        public List<Statement> getCopyright() {
            if (copyright == null) {
                copyright = new ArrayList<Statement>();
            }
            return this.copyright;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Disclaimer" type="{http://www.tdwg.org/schemas/abcd/2.06}Statement" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "disclaimer"
    })
    public static class Disclaimers {

        @XmlElement(name = "Disclaimer", required = true)
        protected List<Statement> disclaimer;

        /**
         * Gets the value of the disclaimer property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the disclaimer property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDisclaimer().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Statement }
         * 
         * 
         */
        public List<Statement> getDisclaimer() {
            if (disclaimer == null) {
                disclaimer = new ArrayList<Statement>();
            }
            return this.disclaimer;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="IPRDeclaration" type="{http://www.tdwg.org/schemas/abcd/2.06}Statement" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "iprDeclaration"
    })
    public static class IPRDeclarations {

        @XmlElement(name = "IPRDeclaration", required = true)
        protected List<Statement> iprDeclaration;

        /**
         * Gets the value of the iprDeclaration property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the iprDeclaration property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getIPRDeclaration().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Statement }
         * 
         * 
         */
        public List<Statement> getIPRDeclaration() {
            if (iprDeclaration == null) {
                iprDeclaration = new ArrayList<Statement>();
            }
            return this.iprDeclaration;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="License" type="{http://www.tdwg.org/schemas/abcd/2.06}Statement" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "license"
    })
    public static class Licenses {

        @XmlElement(name = "License", required = true)
        protected List<Statement> license;

        /**
         * Gets the value of the license property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the license property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getLicense().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Statement }
         * 
         * 
         */
        public List<Statement> getLicense() {
            if (license == null) {
                license = new ArrayList<Statement>();
            }
            return this.license;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="TermsOfUse" type="{http://www.tdwg.org/schemas/abcd/2.06}Statement" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "termsOfUse"
    })
    public static class TermsOfUseStatements {

        @XmlElement(name = "TermsOfUse", required = true)
        protected List<Statement> termsOfUse;

        /**
         * Gets the value of the termsOfUse property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the termsOfUse property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTermsOfUse().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Statement }
         * 
         * 
         */
        public List<Statement> getTermsOfUse() {
            if (termsOfUse == null) {
                termsOfUse = new ArrayList<Statement>();
            }
            return this.termsOfUse;
        }

    }

}
