//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.16 at 11:51:40 AM CET 
//


package nl.naturalis.oaipmh.api.jaxb.abcd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Organisation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Organisation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OrganisationGUID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Name" type="{http://www.tdwg.org/schemas/abcd/2.06}Label"/>
 *         &lt;element name="OrgUnits" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="OrgUnit" type="{http://www.tdwg.org/schemas/abcd/2.06}StringL" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Organisation", propOrder = {
    "organisationGUID",
    "name",
    "orgUnits"
})
public class Organisation {

    @XmlElement(name = "OrganisationGUID")
    protected String organisationGUID;
    @XmlElement(name = "Name", required = true)
    protected Label name;
    @XmlElement(name = "OrgUnits")
    protected Organisation.OrgUnits orgUnits;

    /**
     * Gets the value of the organisationGUID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrganisationGUID() {
        return organisationGUID;
    }

    /**
     * Sets the value of the organisationGUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrganisationGUID(String value) {
        this.organisationGUID = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link Label }
     *     
     */
    public Label getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link Label }
     *     
     */
    public void setName(Label value) {
        this.name = value;
    }

    /**
     * Gets the value of the orgUnits property.
     * 
     * @return
     *     possible object is
     *     {@link Organisation.OrgUnits }
     *     
     */
    public Organisation.OrgUnits getOrgUnits() {
        return orgUnits;
    }

    /**
     * Sets the value of the orgUnits property.
     * 
     * @param value
     *     allowed object is
     *     {@link Organisation.OrgUnits }
     *     
     */
    public void setOrgUnits(Organisation.OrgUnits value) {
        this.orgUnits = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="OrgUnit" type="{http://www.tdwg.org/schemas/abcd/2.06}StringL" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "orgUnit"
    })
    public static class OrgUnits {

        @XmlElement(name = "OrgUnit", required = true)
        protected List<StringL> orgUnit;

        /**
         * Gets the value of the orgUnit property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the orgUnit property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOrgUnit().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link StringL }
         * 
         * 
         */
        public List<StringL> getOrgUnit() {
            if (orgUnit == null) {
                orgUnit = new ArrayList<StringL>();
            }
            return this.orgUnit;
        }

    }

}
