//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2015.12.16 at 11:51:40 AM CET
//
/**
 * JAXB classes for ABCD. Generated by xjc. Namespace prefix added manually!!!
 */
@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.tdwg.org/schemas/abcd/2.06",
		elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
		xmlns = @XmlNs(prefix = "abcd", namespaceURI = "http://www.tdwg.org/schemas/abcd/2.06"))
package nl.naturalis.oaipmh.api.jaxb.abcd;

import javax.xml.bind.annotation.XmlNs;

