//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.16 at 11:51:40 AM CET 
//


package nl.naturalis.oaipmh.api.jaxb.abcd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Elements only used for palaeontological units
 * 			
 * 
 * <p>Java class for PalaeontologicalUnit complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PalaeontologicalUnit">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Preservation" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Completeness" type="{http://www.tdwg.org/schemas/abcd/2.06}StringL" minOccurs="0"/>
 *                   &lt;element name="Form" type="{http://www.tdwg.org/schemas/abcd/2.06}StringL" minOccurs="0"/>
 *                   &lt;element name="Matrix" type="{http://www.tdwg.org/schemas/abcd/2.06}StringL" minOccurs="0"/>
 *                   &lt;element name="Mineralisation" type="{http://www.tdwg.org/schemas/abcd/2.06}StringL" minOccurs="0"/>
 *                   &lt;element name="Taphonomy" type="{http://www.tdwg.org/schemas/abcd/2.06}StringL" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="TimeRange" type="{http://www.tdwg.org/schemas/abcd/2.06}String" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PalaeontologicalUnit", propOrder = {
    "preservation",
    "timeRange"
})
public class PalaeontologicalUnit {

    @XmlElement(name = "Preservation")
    protected PalaeontologicalUnit.Preservation preservation;
    @XmlElement(name = "TimeRange")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String timeRange;

    /**
     * Gets the value of the preservation property.
     * 
     * @return
     *     possible object is
     *     {@link PalaeontologicalUnit.Preservation }
     *     
     */
    public PalaeontologicalUnit.Preservation getPreservation() {
        return preservation;
    }

    /**
     * Sets the value of the preservation property.
     * 
     * @param value
     *     allowed object is
     *     {@link PalaeontologicalUnit.Preservation }
     *     
     */
    public void setPreservation(PalaeontologicalUnit.Preservation value) {
        this.preservation = value;
    }

    /**
     * Gets the value of the timeRange property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeRange() {
        return timeRange;
    }

    /**
     * Sets the value of the timeRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeRange(String value) {
        this.timeRange = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Completeness" type="{http://www.tdwg.org/schemas/abcd/2.06}StringL" minOccurs="0"/>
     *         &lt;element name="Form" type="{http://www.tdwg.org/schemas/abcd/2.06}StringL" minOccurs="0"/>
     *         &lt;element name="Matrix" type="{http://www.tdwg.org/schemas/abcd/2.06}StringL" minOccurs="0"/>
     *         &lt;element name="Mineralisation" type="{http://www.tdwg.org/schemas/abcd/2.06}StringL" minOccurs="0"/>
     *         &lt;element name="Taphonomy" type="{http://www.tdwg.org/schemas/abcd/2.06}StringL" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "completeness",
        "form",
        "matrix",
        "mineralisation",
        "taphonomy"
    })
    public static class Preservation {

        @XmlElement(name = "Completeness")
        protected StringL completeness;
        @XmlElement(name = "Form")
        protected StringL form;
        @XmlElement(name = "Matrix")
        protected StringL matrix;
        @XmlElement(name = "Mineralisation")
        protected StringL mineralisation;
        @XmlElement(name = "Taphonomy")
        protected StringL taphonomy;

        /**
         * Gets the value of the completeness property.
         * 
         * @return
         *     possible object is
         *     {@link StringL }
         *     
         */
        public StringL getCompleteness() {
            return completeness;
        }

        /**
         * Sets the value of the completeness property.
         * 
         * @param value
         *     allowed object is
         *     {@link StringL }
         *     
         */
        public void setCompleteness(StringL value) {
            this.completeness = value;
        }

        /**
         * Gets the value of the form property.
         * 
         * @return
         *     possible object is
         *     {@link StringL }
         *     
         */
        public StringL getForm() {
            return form;
        }

        /**
         * Sets the value of the form property.
         * 
         * @param value
         *     allowed object is
         *     {@link StringL }
         *     
         */
        public void setForm(StringL value) {
            this.form = value;
        }

        /**
         * Gets the value of the matrix property.
         * 
         * @return
         *     possible object is
         *     {@link StringL }
         *     
         */
        public StringL getMatrix() {
            return matrix;
        }

        /**
         * Sets the value of the matrix property.
         * 
         * @param value
         *     allowed object is
         *     {@link StringL }
         *     
         */
        public void setMatrix(StringL value) {
            this.matrix = value;
        }

        /**
         * Gets the value of the mineralisation property.
         * 
         * @return
         *     possible object is
         *     {@link StringL }
         *     
         */
        public StringL getMineralisation() {
            return mineralisation;
        }

        /**
         * Sets the value of the mineralisation property.
         * 
         * @param value
         *     allowed object is
         *     {@link StringL }
         *     
         */
        public void setMineralisation(StringL value) {
            this.mineralisation = value;
        }

        /**
         * Gets the value of the taphonomy property.
         * 
         * @return
         *     possible object is
         *     {@link StringL }
         *     
         */
        public StringL getTaphonomy() {
            return taphonomy;
        }

        /**
         * Sets the value of the taphonomy property.
         * 
         * @param value
         *     allowed object is
         *     {@link StringL }
         *     
         */
        public void setTaphonomy(StringL value) {
            this.taphonomy = value;
        }

    }

}
