//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.16 at 11:51:40 AM CET 
//


package nl.naturalis.oaipmh.api.jaxb.abcd;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RecordBasisEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RecordBasisEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}Name">
 *     &lt;enumeration value="PreservedSpecimen"/>
 *     &lt;enumeration value="LivingSpecimen"/>
 *     &lt;enumeration value="FossileSpecimen"/>
 *     &lt;enumeration value="OtherSpecimen"/>
 *     &lt;enumeration value="HumanObservation"/>
 *     &lt;enumeration value="MachineObservation"/>
 *     &lt;enumeration value="DrawingOrPhotograph"/>
 *     &lt;enumeration value="MultimediaObject"/>
 *     &lt;enumeration value="AbsenceObservation"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "RecordBasisEnum")
@XmlEnum
public enum RecordBasisEnum {

    @XmlEnumValue("PreservedSpecimen")
    PRESERVED_SPECIMEN("PreservedSpecimen"),
    @XmlEnumValue("LivingSpecimen")
    LIVING_SPECIMEN("LivingSpecimen"),
    @XmlEnumValue("FossileSpecimen")
    FOSSILE_SPECIMEN("FossileSpecimen"),
    @XmlEnumValue("OtherSpecimen")
    OTHER_SPECIMEN("OtherSpecimen"),
    @XmlEnumValue("HumanObservation")
    HUMAN_OBSERVATION("HumanObservation"),
    @XmlEnumValue("MachineObservation")
    MACHINE_OBSERVATION("MachineObservation"),
    @XmlEnumValue("DrawingOrPhotograph")
    DRAWING_OR_PHOTOGRAPH("DrawingOrPhotograph"),
    @XmlEnumValue("MultimediaObject")
    MULTIMEDIA_OBJECT("MultimediaObject"),
    @XmlEnumValue("AbsenceObservation")
    ABSENCE_OBSERVATION("AbsenceObservation");
    private final String value;

    RecordBasisEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RecordBasisEnum fromValue(String v) {
        for (RecordBasisEnum c: RecordBasisEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
