//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.29 at 03:39:37 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(
		namespace = "http://purl.org/dc/elements/1.1/",
		xmlns=@javax.xml.bind.annotation.XmlNs(namespaceURI = "http://purl.org/dc/elements/1.1/", prefix = "dc"),
		elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED
)
package org.purl.dc.elements._1;
